version: '3.1' # version of dockercompose (need >3.1 for healthcheck)
services:

  # building the app using the Dockerfile
  homeapp:
    build: .
    image: home:1.2 # Tag the image
    ports:
      - "8080:8080"
    env_file:
      - ../.env

volumes:
                # use RDS instead of local mysql
  mysql-data:   # Define the volume (so it survives container restarts)
    external: true