version: '3.1' # version of dockercompose (need >3.1 for healthcheck)

services:
  homeapp:
    build: .
    image: backend:1.10 # Tag the image
    ports:
      - "8080:8080"
    environment:
      ECR_REPO_URL: $ECR_REPO_URL
      RDS_HOST_URL: $RDS_HOST_URL
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      AWS_CERTIFICATE_ARN: $AWS_CERTIFICATE_ARN
      user_pool_client_clientid: $user_pool_client_clientid
      user_pool_client_secret: $user_pool_client_secret

volumes:
  mysql-data:   # Define the volume (so it survives container restarts)