version: '3.1' # version of dockercompose (need >3.1 for healthcheck)
services:

  # building the app using the Dockerfile
  paymentapp:
    build: .
    image: paymentapp:1.0 # Tag the image
    ports:
      - "8083:8083"
