version: '3'

services:
  feed:
    build:
      context: ./feed
    ports:
      - "8080:8080"
    depends_on:
      - purchase

  purchase:
    build:
      context: ./purchase
    expose:
      - "8081" # expose port 8081 to be used by feed service (not exposed to host machine)
